"""
FastAPI application for Fixation Bolding – converting PDF to EPUB.

API shape:
- GET / -> simple one-page HTML with file input.
- POST /convert -> multipart/form-data file named "file".
  Returns the generated EPUB as an attachment.

Workflow:
1. Verify file is PDF (.pdf extension and %PDF magic).
|2. Extract text & layout using pymupdf. Keep font size to detect headings.
3. Apply fixation prefix to each word.
4. Build EPUB with ebooklib, one chapter per heading.
5. Return EPUB.

Error handling: 400 for bad file, 422 for scanned/no-text PDFs, 413 for size >50MB.
"""
import io
import os
from fastapi import FastAPI, File, UploadFile, HTTPException, Response
from fastapi.responses import HTMLResponse

import pymupdf  # PyMuPDF
from ebooklib import epub

app = FastAPI()

MAX_SIZE_MB = 50
MAX_SIZE_BYTES = MAX_SIZE_MB * 1024 * 1024

# Simple one-page HTML
HTML_PAGE = """
<!doctype html>
<title>Fixation Bolding \u2013 PDF to EPUB</title>
<h1>Fixation Bolding \u2013 PDF to EPUB</h1>
<form id='uploadForm' enctype='multipart/form-data'>
  <label for='file'>Choose PDF file (max 50\u202fMB):</label><br>
  <input type='file' id='file' name='file' accept='.pdf' required><br><br>
  <button type='submit'>Convert</button>
</form>
<div id='status'></div>
<script>
  const form = document.getElementById('uploadForm');
  const status = document.getElementById('status');
  form.addEventListener('submit', async e => {
    e.preventDefault();
    status.textContent = 'Converting…';
    const formData = new FormData(form);
    const response = await fetch('/convert', {
      method: 'POST',
      body: formData
    });
    if (response.ok) {
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'converted.epub';
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);
      status.textContent = 'Done!';
    } else {
      const error = await response.json();
      status.textContent = 'Error: ' + error.detail;
    }
  });
</script>
"""

@app.get("/")
def read_root():
    return HTMLResponse(HTML_PAGE)


def validate_pdf(file_bytes: bytes) -> None:
    if len(file_bytes) > MAX_SIZE_BYTES:
        raise HTTPException(status_code=413, detail=f"File too large. Max {MAX_SIZE_MB}\u202fMB allowed.")
    if not file_bytes.startswith(b"%PDF"):
        raise HTTPException(status_code=400, detail="Uploaded file is not a PDF.")


def extract_text_and_headings(doc: pymupdf.Document) -> tuple[list[str], list[int]]:
    paragraphs: list[str] = []
    heading_levels: list[int] = []
    all_heights: list[float] = []
    for page in doc:
        blocks = page.get_text('blocks')
        for _, _, _, _, text, _, _ in blocks:
            if text.strip():
                all_heights.append(page.rect.height)
    avg_height = sum(all_heights) / len(all_heights) if all_heights else 0
    for page in doc:
        blocks = page.get_text('blocks')
        for _, _, _, _, text, _, _ in blocks:
            if not text.strip():
                continue
            height = page.rect.height
            is_heading = height > 1.4 * avg_height
            paragraphs.append(text.strip())
            heading_levels.append(1 if is_heading else None)
    return paragraphs, heading_levels


def apply_fixation(text: str) -> str:
    import re
    def repl(match: re.Match) -> str:
        word = match.group(0)
        if not re.match(r'^[A-Za-z]+$', word):
            return word
        n = (len(word) + 1) // 2
        return f"<strong>{word[:n]}</strong>{word[n:] }"
    return re.sub(r"\b[A-Za-z]+\b", repl, text)


def build_epub(paragraphs: list[str], heading_levels: list[int]) -> bytes:
    book = epub.EpubBook()
    book.set_identifier('fixation-bolding')
    book.set_title('Fixation Bolding EPUB')
    book.set_language('en')
    spine = []
    cover = epub.EpubHtml(title='Cover', file_name='cover.xhtml', lang='en')
    cover.content = '<h1>Generated by Fixation Bolding</h1>'
    book.add_item(cover)
    spine.append(cover)
    chapter_id = 0
    for idx, para in enumerate(paragraphs):
        level = heading_levels[idx]
        if level == 1:
            chapter_id += 1
            chap = epub.EpubHtml(title=f'Chapter {chapter_id}', file_name=f'chap_{chapter_id}.xhtml', lang='en')
            chap.content = f'<h1>{apply_fixation(para)}</h1>'
            book.add_item(chap)
            spine.append(chap)
        else:
            last = spine[-1]
            if getattr(last, 'content', None) is None:
                last.content = ''
            last.content += f'<p>{apply_fixation(para)}</p>'
    book.spine = spine
    book.toc = [(chap, []) for chap in spine[1:]]
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())
    output_path = 'output.epub'
    epub.write_epub(output_path, book, {})
    with open(output_path, 'rb') as f:
        return f.read()

@app.post("/convert")
async def convert(file: UploadFile = File(...)):
    if file.content_type not in ("application/pdf", "application/octet-stream"):
        raise HTTPException(status_code=400, detail="Only PDF files are accepted.")
    file_bytes = await file.read()
    validate_pdf(file_bytes)
    try:
        doc = pymupdf.open(stream=file_bytes, filetype="pdf")
    except Exception:
        raise HTTPException(status_code=422, detail="Failed to parse PDF. It may be corrupted or scanned.")
    paragraphs, heading_levels = extract_text_and_headings(doc)
    if not paragraphs:
        raise HTTPException(status_code=422, detail="The PDF appears to contain only scanned images. Text-based PDFs are required.")
    epub_bytes = build_epub(paragraphs, heading_levels)
    return Response(content=epub_bytes, media_type='application/epub+zip', headers={'Content-Disposition': 'attachment; filename=converted.epub'})
